#!/usr/bin/env node
// Render a markdown business plan to a clean branded PDF.
// Uses `marked` for MD->HTML and the cached Chromium (--print-to-pdf) for PDF.
// Usage: node makepdf.mjs <plan.md> <out.pdf> [title]
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawnSync } from "node:child_process";
import { marked } from "marked";

const [mdFile, outPdf, title = "Business Plan"] = process.argv.slice(2);
const md = fs.readFileSync(mdFile, "utf8");
const body = marked.parse(md);

const html = `<!doctype html><html><head><meta charset="utf-8"><style>
@page { margin: 18mm 16mm; }
* { box-sizing: border-box; }
body { font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; color: #1a1a1a; line-height: 1.5; font-size: 12.5px; }
h1 { font-size: 26px; color: #0b0b0c; border-bottom: 3px solid #D4AF37; padding-bottom: 8px; margin: 0 0 6px; }
h2 { font-size: 17px; color: #0b0b0c; margin: 22px 0 6px; border-left: 4px solid #D4AF37; padding-left: 9px; }
h3 { font-size: 14px; color: #333; margin: 16px 0 4px; }
p, li { font-size: 12.5px; }
em { color: #555; }
strong { color: #0b0b0c; }
hr { border: none; border-top: 1px solid #ddd; margin: 18px 0; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 12px; }
th, td { border: 1px solid #ccc; padding: 6px 9px; text-align: left; }
th { background: #f4ecd8; color: #0b0b0c; }
tr:nth-child(even) td { background: #faf8f2; }
code { background: #f3f3f3; padding: 1px 4px; border-radius: 3px; }
a { color: #b8860b; }
.brandfoot { margin-top: 26px; padding-top: 10px; border-top: 2px solid #D4AF37; font-size: 11px; color: #888; }
</style></head><body>${body}
<div class="brandfoot">${process.env.ACP_BRAND ? process.env.ACP_BRAND + " · " : ""}generated by AutoClipperPro</div>
</body></html>`;

const tmpHtml = path.join(os.tmpdir(), `bbb-pdf-${Date.now()}.html`);
fs.writeFileSync(tmpHtml, html, "utf8");

const chrome =
  process.env.CHROME_PATH ||
  path.join(os.homedir(), "AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe");

const fileUrl = "file:///" + tmpHtml.replace(/\\/g, "/");
const r = spawnSync(chrome, [
  "--headless=new", "--disable-gpu", "--no-sandbox",
  "--no-pdf-header-footer",
  `--print-to-pdf=${outPdf}`, fileUrl,
], { stdio: "inherit" });

fs.rmSync(tmpHtml, { force: true });
if (r.status !== 0 || !fs.existsSync(outPdf)) { console.error("PDF render failed (chrome status " + r.status + ")"); process.exit(1); }
console.log(JSON.stringify({ saved: outPdf, bytes: fs.statSync(outPdf).size }, null, 2));
